version: "3"
networks:
  ms-user:
    name: ms-user
volumes:
  chamster-user-db-data:
    name: chamster-user-db-data
  chamster-user-db-config:
    name: chamster-user-db-config

services:
  ms-user-db:
    image: mongo:latest
    container_name: ms-user-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - ms-user
    volumes:
      - type: volume
        target: /data/db
        source: chamster-user-db-data
      - type: volume
        target: /data/configdb
        source: chamster-user-db-config

  ms-user-db-express:
    image: mongo-express
    container_name: ms-user-db-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: ms-user-db
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - ms-user-db
    networks:
      - ms-user
